#es el archivo de configuración de Pytest. Define cómo se ejecutan las pruebas



[pytest]
testpaths = backend/tests #Indica dónde buscar archivos de tests
markers =
    unit: pruebas unitarias (sin dependencias externas)
    integration: pruebas de integracion (requieren servicios)

