apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurante-config
  namespace: restaurante
data:
  DATABASE_ENGINE: "mongo"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "restaurant_postgres_db"
  MONGO_DB: "restaurant_mongo_db"
  MONGO_URL: "mongodb://mongos:27017/restaurant_mongo_db"
  KEYCLOAK_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "restaurant-realm"
  KEYCLOAK_CLIENT_ID: "restaurant-client"

  #Define variables de entorno públicas que todos los pods
